### ISSUE TITLE
'develop' branch: getCollection() fails to create ~/.auxiliaries/collections.rds

### ISSUE THREAD

**Issue by fdetsch** [MatMatt/MODIS#1]
Encountered an error related to `getCollection`. The following code

```{r getCollection}
getCollection('MYD13Q1', forceCheck = TRUE)
```
results in 

```{r error}
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'F:/DATA_F~1/process/.auxiliaries//collections.rds', probable reason 'No such file or directory'
```

**Comment by MatMatt** [comment]
hi habe heute leider keinen pc zur Verfügung.
die Schritte die bei getCollection !passieren sollten:
file.exists? .aux/coll...rds
yes use it/ update it
no use file in /external update it copy to .aux

ich glaube das Problem ist im lazyload. dass man hier nicht diese Abfrage
file.exists machen kann. ich wuerde dies also eher nicht als lazyload laden.

es gibt die funktion setPath oder correctPath bin mir nicht mehr sicher.
sie ist dazu da zu garantieren das ein pfad angelegt wird und richtig
geschrieben wird, und zwar in allen Plattforms sei es für cmd als alle
anderen situationen. kann also auch genutzt weden um cmd commands zu
generieren. ist eine meiner Lieblinge ;)

ihth
lg m
Am 01.10.2015 12:51 nachm. schrieb "Florian Detsch" <
notifications@github.com>:

**Comment by fdetsch** [comment]
Forgot to move 'inst/external/collections.rds' from SVN to GitHub, i.e. initial copying to '~/.auxiliaries/collections.rds' failed. Function call seems to work now. 

```{r getCollection}
> getCollection('MYD13Q1', forceCheck = TRUE)
Updating collections from LPDAAC for platform: Aqua 
Loading required package: RCurl
Loading required package: bitops
Loading required package: XML
$MYD13Q1
[1] "006"
```
