### ISSUE TITLE
runGdal broken after "Important Changes to LP DAAC Data Access"?

### ISSUE THREAD

**Issue by dk-forestry** [MatMatt/MODIS#10]
I tried to download MODIS data using one of the examples from the runGdal-documentation:

`runGdal( job="LSTaustria", product="MOD11A1", tileH=18:19,tileV=4, begin="2010001", end="2010005", SDSstring="1", outProj="asIn")`

However, I only get this messages:

`Getting file from: LPDAAC`
`############################`
`trying URL 'http://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.005/2010.01.01/MOD11A1.A2010001.h19v04.005.2010007011204.hdf'`
`Remote connection failed! Re-try: 1`
`Getting file from: LAADS`
`############################`
`trying URL 'ftp://ladsftp.nascom.nasa.gov/allData/5/MOD11A1/2010/001/MOD11A1.A2010001.h19v04.005.2010007011204.hdf'
`Remote connection failed! Re-try: 2`

This continues 50 times and than fails.

It seems that since June 22, 2016, it is now necessary to log in using Earthdata login credentials to obtain data from LP DAAC (https://lpdaac.usgs.gov/about/news_archive/important_changes_lp_daac_data_access). This means that script users will need to modify scripts to allow for this change.

Is it possible that this change causes the problem?
If yes, is there currently any workaround?

**Comment by fdetsch** [comment]
True story. Something has changed on the download side and we need to have a look into it soon. How about LAADS, did it work? For me, 

```
MODISoptions(MODISserverOrder = c("LAADS", "LPDAAC"))

runGdal(job = "LSTaustria", product = "MOD11A1", tileH = 18:19, tileV = 4, 
        begin = "2010011", end = "2010015", SDSstring = "1", wait = 3L)
```

works just fine since LAADS doesn't seem to be affected.

**Comment by MatMatt** [comment]
There are mechanisms for adding login credentials. When writing the the
package I already thought about that I thing the MERISland data (which was
never operative) required a login.

I think the login credential should go into: MODIS:::MODIS_FTPinfo

And probably it would be good to have a function to manipulate
...$ftpstrings.

At the end MODIS:::ModisFileDownloader needs to be enabled to use the
credentials for each download function (aria2 or download.file). I know for
the latter that credentials can be used.



At the end it should go in  FTPinfo (can't recall the exact name).

Am 12.08.2016 07:19 schrieb "Florian Detsch" <notifications@github.com>:

**Comment by khufkens** [comment]
Can't offer a solution but it affects some of my personal tools as well. They did the scientific community a disservice with this in my opinion. One of the reasons MODIS is so popular is that you do not have to jump through hoops to get to the data (unlike for ESA products).

**Comment by sonjnow** [comment]
> MODISoptions(MODISserverOrder = c("LAADS", "LPDAAC"))

Yes, that did indeed work for me. Thanks for the hint! :)

**Comment by MatMatt** [comment]
The simplest solution would be to paste() the username and pw directly into the url. 
See http://stackoverflow.com/questions/8510528/download-file-from-web-via-r-console
...
USERNAME = 'your username'
PASSWORD = 'your password'

 ## Url for downloading - Does contain login credentials. Use this one!! 
 url <- paste( 'http://statcounter.com/p7447608/csv/download_log_file?ufrom=1323783441&uto=1323860282&form_user=', USERNAME, '&form_pass=', PASSWORD, sep = '') 
...

I tried to get the naming of required parameters (here '&form_user', and '&form_pass'), but I wasn't able to find them. If we know how to compose the URL we solve the issue. 

Here an example url to test:
http://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.006/2000.03.10/MOD11A1.A2000070.h21v16.006.2015057071438.hdf

**Comment by khufkens** [comment]
This might work:
getURL("https://api.picloud.com/job/?jids=12", userpwd="key:secret", httpauth = 1L) 

[https://stackoverflow.com/questions/10157969/rcurl-http-authentication-when-site-responds-with-http-401-code-without-www-aut](https://stackoverflow.com/questions/10157969/rcurl-http-authentication-when-site-responds-with-http-401-code-without-www-aut)

**Comment by khufkens** [comment]
```R
library(RCurl)
agent="Mozilla/5.0" #or whatever 
dataurl = "http://e4ftl01.cr.usgs.gov/MOLT/MOD09A1.006/2001.01.09/MOD09A1.A2001009.h13v01.006.2015140120258.hdf.xml"

html=getURL(dataurl,
            cookiejar="cookies.txt",
            cookie="cookies.txt",
            useragent = agent,
            followlocation = TRUE,
            netrc = TRUE,
            verbose=TRUE)

print(html)

# with a .netrc formated as
# machine urs.earthdata.nasa.gov
#         login username
#         password userpassword
```

This code gives a return, but it's a faulty one. Ironically you get the same error using [their example online.
](https://lpdaac.usgs.gov/sites/default/files/public/get_data/docs/Command%20Line%20Access%20Tips%20for%20Utilizing%20Earthdata%20Login.docx)

**Comment by MatMatt** [comment]
Creating a .netrc file works for me (2.2 LDAP):
http://docs.opendap.org/index.php/DAP_Clients_-_Authentication#LDAP
and then:

url <- 'http://e4ftl01.cr.usgs.gov/MOLT/MOD13A1.006/2001.03.06/MOD13A1.A2001065.h17v00.006.2015142191043.hdf'
dest <- 'delme.hdf'

# -n forces curl to use the .netrc file for autentification.
download.file(url,destfile = dest,method = 'curl', extra=paste0('-n -L -c ~/.cookies.txt -b ~/.cookies.txt'))

whereas this does not work (it works only after creating the .netrc file):
download.file(url,destfile = 'yxx.hdf',method = 'curl', extra=paste0('-u myuser:mypw -L -c ~/.cookies.txt -b ~/.cookies.txt'))

I still  prefer to find something that does not require an external file. Then we need also to see how it is with other dlmethods (wget, aria2, internal...). (Checking now)

**Comment by MatMatt** [comment]
This could be the function to create the netrc file on Unixoides (I couldn't test it so far as I am on Windows here):

```
lpdaacLogin <- function()
{
  if(.Platform$OS.type=="unix")
  {
    message('Warning: this function creates a plain text file in your home directory with login information for "urs.earthdata.nasa.gov"!')
    
    netfile <- file("~/.netrc", open="wt")
    write('machine urs.earthdata.nasa.gov', netfile)
    x <- readline("Insert your earthdata USERNAME (see: urs.earthdata.nasa.gov): ")  
    write(paste('login',x), netfile)
    x <- readline("Insert your earthdata PASSWORD: ")  
    write(paste('password',x), netfile)
    close(netfile)    
    Sys.chmod('~/.netrc', mode = "600", use_umask = TRUE)
  } else
  {
    stop('netrc file can not be created on windos yet. Until we found a solution please set "LAADS" as promaty server on "MODISoptions"')
  }
}
```

We could generate a message when a user tries to dl from LPDAAC and has no netrc file in his home. something like "LPDAAC requires authentification run 'lpdaacLogin()' and insert your earthdata login. or remove LPDAAC from 'serverOder' in 'MODISoptions'"

**Comment by thiagoveloso** [comment]
The folks from EarthData have released detailed instructions on how to access the servers using command line:

http://disc.sci.gsfc.nasa.gov/registration/registration-for-data-access

According to some tests I've made, both netrc file AND cookies must be enabled in order to download MODIS products.

**Comment by fdetsch** [comment]
Solved with the introduction of `lpdaacLogin()` (ceeb57906f3dc26a45e39fff3c784d9c97d810cf) and related adjustments in `getHdf()`.

**Comment by WillemVervoort** [comment]
Hi all, this remains a problem. I have used lpdaacLogin() and have no problem with creating netrc
Windows,  R3.4.3

I am also logged in into Earthdata via a web browser
MODISoptions(MODISserverOrder = "LPDAAC")

product = "MOD16A2"
lpdaacLogin()

hdf = getHdf("MOD16A2", begin = "2017.01.01", end = "2017.01.10",
              tileH = 21, tileV = 8)
hdf


Resolving urs.earthdata.nasa.gov (urs.earthdata.nasa.gov)... 198.118.243.33
Connecting to urs.earthdata.nasa.gov (urs.earthdata.nasa.gov)|198.118.243.33|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

Any clues?
