### ISSUE TITLE
runGdal date issue

### ISSUE THREAD

**Issue by Saadi4469** [MatMatt/MODIS#107]
Hello,

```
runGdal(product= "MOD13Q1",begin = "2015001",end = "2020366",tileH = h,tileV = v,SDSstring = B,
        job = "Qual", outProj="GEO", datum="WGS84")
```
The above line is downloading files (pixel reliability band) with wrong begin date, the downloaded files are starting from 2019 instead of 2015! It's weird because when I use the same code for the 1st band (NDVI), it starts downloading files according to the begin date 2015001.

**Comment by Saadi4469** [comment]
Changing the output path to a new/different folder under MODISoptions solves this issue.

**Comment by fdetsch** [comment]
Thanks again. Please let us know if you get to the bottom of what you described in the first comment.
