### ISSUE TITLE
strsplit error

### ISSUE THREAD

**Issue by juanenbici** [MatMatt/MODIS#111]
Hi. When I try to download and process MODIS data with MODIS R package, I get this strange strsplit error.

`runGdal( product="MOD11A1", begin="2010001", end="2010005", SDSstring="101")`

what I get after select some tiles:

`########################`
`outProj          =  asIn `
`pixelSize        =  asIn `
`resamplingType   =  near `
`Output directory =  C:/**************************/MOD11A1.006_20210526092347  (no 'job' name specified, generated (date/time based))`
`########################`
`Downloading structure on 'LPDAAC' for: MOD11A1.006`
`Hm, I have to search for the file. Next time provide the full path and I'll be very fast!`
`Error in strsplit(x, ":") : non-character argument  `

Don't know what is happening here. Thanks

**Comment by juanenbici** [comment]
After changing the `localArcPath`, now is not giving me this error anymore but is giving me the following loop error 


´############################´
´Remote connection failed! Re-try: 24 ´
´Getting file from: LAADS ´
´############################´
´Remote connection failed! Re-try: 25 ´
´Getting file from: LPDAAC ´
´############################´

**Comment by labguyvancouver** [comment]
I am having the same issue. Any resolution yet?

**Comment by fdetsch** [comment]
@ramonmelser @juanenbici I fail to reproduce this error. Can you maybe provide the output of `traceback()` to give me an idea where the error occurs? Or alternatively, run the above code with `debug(MODIS::runGdal)` enabled?

**Comment by fdetsch** [comment]
Please see https://github.com/MatMatt/MODIS/issues/114#issuecomment-903897048 and comments below for a possible solution. Closing this due to to inactivity.
