### ISSUE TITLE
Help downloading MODIS data in R 

### ISSUE THREAD

**Issue by Avtober** [MatMatt/MODIS#114]
Hi, I am trying to download NDVI from MODIS and used the following code but am having issues:

devtools::install_github("MatMatt/MODIS", ref = "develop")
library(MODIS)

MODIS = runGdal("MOD13Q1", collection = "006", 
              tileH = 20, tileV = 11, 
              begin = "2000.02.18", end = "2010.03.10", job = "MOD13Q1",
              SDSstring = "110000000000") # extract NDVI and EVI

I get the following error message:
########################
outProj          =  asIn 
pixelSize        =  asIn 
resamplingType   =  near 
Output directory =  C:/Users/avtob/AppData/Local/Temp/RtmpKeYFk0/MODIS_ARC/PROCESSED/MOD13Q1.006_20210816171601  (no 'job' name specified, generated (date/time based))
########################
Downloading structure on 'LPDAAC' for: MOD13Q1.006
Hm, I have to search for the file. Next time provide the full path and I'll be very fast!
Error in strsplit(x, ":") : non-character argument

Please help, I am not sure what it means by provide the full path, how do I do this? 

Thanks 
Anya

**Comment by fdetsch** [comment]
@Avtober Can you have a look at https://github.com/MatMatt/MODIS/issues/111#issuecomment-902473477 (similar issue) and try to provide the required information?

**Comment by Avtober** [comment]
Hi @fdetsch, If I run the traceback i get the following:
> traceback()
7: strsplit(x, ":")
6: getSdsNames(SDSnames)
5: gsub("\"", "", getSdsNames(SDSnames))
4: getSds(HdfName = y, SDSstring = SDSstring)
3: FUN(X[[i]], ...)
2: lapply(files, function(y) {
       getSds(HdfName = y, SDSstring = SDSstring)
   })
1: runGdal("MOD13Q1", collection = "006", tileH = 20, tileV = 11, 
       begin = "2000.02.18", end = "2010.03.10", job = "MOD13Q1", 
       SDSstring = "110000000000")

If I run it in debug mode I get the following:
debugging in: runGdal("MOD13Q1", collection = "006", tileH = 20, 
    tileV = 11, begin = "2000.02.18", end = "2010.03.10", 
    job = "MOD13Q1", SDSstring = "110000000000")
debug: {
    opts <- combineOptions(...)
    if (!opts$gdalOk) {
        stop("GDAL not installed or configured, read in '?MODISoptions' for help")
    }
    product <- getProduct(product, quiet = TRUE, collection = collection)
    tLimits <- transDate(begin = begin, end = end)
    dataFormat <- toupper(opts$dataFormat)
    if (dataFormat == "HDF-EOS") {
        dataFormat <- "HDF4IMAGE"
    }
    else if (dataFormat == "GEOTIFF") {
        dataFormat <- "GTIFF"
    }
    if (is.null(opts$gdalOutDriver)) {
        opts$gdalOutDriver = getGdalWriteDrivers()
        options(MODIS_gdalOutDriver = opts$gdalOutDriver)
    }
    dataFormat = checkGdalWriteDriver(dataFormat)
    xtn = getExtension(dataFormat)
    args = as.list(match.call())
    args[[1]] <- NULL
    args = args[names(args) %in% c("extent", "tileH", 
        "tileV")]
    names(args)[names(args) == "extent"] = "x"
    if (missing(extent) || !inherits(extent, "MODISextent")) {
        extent = if (product@TYPE[1] == "Tile" || (product@TYPE[1] == 
            "CMG" && any(!missing(extent), all(!missing(tileH), 
            !missing(tileV))))) {
            do.call(getTile, append(args, list(outProj = opts$outProj, 
                pixelSize = opts$pixelSize)), envir = parent.frame())
        }
    }
    t_srs <- do.call(OutProj, append(list(product = product, 
        extent = extent), opts))
    tr <- do.call(PixelSize, append(list(extent = extent), opts))
    rt <- do.call(ResamplingType, opts)
    s_srs <- InProj(product)
    te <- TargetExtent(extent, outProj = t_srs)
    bs <- do.call(BlockSize, opts)
    cp <- do.call(OutputCompression, opts)
    co <- c(cp, bs)
    lst_product <- vector("list", length(product@PRODUCT))
    for (z in seq_along(product@PRODUCT)) {
        todo <- paste(product@PRODUCT[[z]], product@CCC[[product@PRODUCT[z]]], 
            sep = ".")
        if (z == 1) {
            if (is.null(job)) {
                job <- paste0(todo[1], "_", format(Sys.time(), 
                  "%Y%m%d%H%M%S"))
                cat("Output directory = ", gsub("//", 
                  "/", paste0(normalizePath(opts$outDirPath, 
                    "/", mustWork = FALSE), "/", 
                    job)), " (no 'job' name specified, generated (date/time based))\n")
            }
            else {
                cat("Output Directory = ", gsub("//", 
                  "/", paste0(normalizePath(opts$outDirPath, 
                    "/", mustWork = FALSE), "/", 
                    job)), "\n")
            }
            cat("########################\n")
            outDir <- file.path(opts$outDirPath, job, fsep = "/")
            outDir <- gsub("//", "/", outDir)
            dir.create(outDir, showWarnings = FALSE, recursive = TRUE)
        }
        lst_todo <- vector("list", length(todo))
        for (u in seq_along(todo)) {
            ftpdirs <- list()
            server = product@SOURCE[[z]]
            if (length(server) > 1) {
                server = server[which(server == opts$MODISserverOrder[1])]
            }
            ftpdirs[[1]] <- as.Date(getStruc(product = strsplit(todo[u], 
                "\\.")[[1]][1], collection = strsplit(todo[u], 
                "\\.")[[1]][2], begin = tLimits$begin, 
                end = tLimits$end, server = server)$dates)
            prodname <- strsplit(todo[u], "\\.")[[1]][1]
            coll <- strsplit(todo[u], "\\.")[[1]][2]
            avDates <- ftpdirs[[1]]
            avDates <- avDates[avDates != FALSE]
            avDates <- avDates[!is.na(avDates)]
            sel <- as.Date(avDates)
            st = correctStartDate(tLimits$begin, sel, prodname, 
                quiet = opts$quiet)
            us = sel >= st & sel <= tLimits$end
            if (sum(us, na.rm = TRUE) > 0) {
                avDates <- avDates[us]
                lst_ofile <- as.list(rep(NA, length(avDates)))
                for (l in seq_along(avDates)) {
                  files <- unlist(getHdf(product = prodname, 
                    collection = coll, begin = avDates[l], end = avDates[l], 
                    extent = extent, checkIntegrity = checkIntegrity, 
                    stubbornness = opts$stubbornness, quiet = opts$quiet, 
                    MODISserverOrder = opts$MODISserverOrder, 
                    forceDownload = forceDownload, wait = opts$wait))
                  files <- files[basename(files) != "NA"]
                  if (checkIntegrity) 
                    files <- files[checkIntegrity(files)]
                  if (length(files) > 0) {
                    SDS = lapply(files, function(y) {
                      getSds(HdfName = y, SDSstring = SDSstring)
                    })
                    NAS <- getNa(SDS[[1]]$SDS4gdal)
                    ofiles <- character(length(SDS[[1]]$SDSnames))
                    for (i in seq_along(SDS[[1]]$SDSnames)) {
                      outname <- paste0(paste0(strsplit(basename(files[1]), 
                        "\\.")[[1]][1:2], collapse = "."), 
                        ".", gsub(SDS[[1]]$SDSnames[i], 
                          pattern = " ", replacement = "_"), 
                        xtn)
                      ofile <- paste0(outDir, "/", outname)
                      gdalSDS <- sapply(SDS, function(x) {
                        x$SDS4gdal[i]
                      })
                      naID <- which(SDS[[1]]$SDSnames[i] == names(NAS))
                      nodataValue = srcnodata = dstnodata = if (length(naID) > 
                        0) 
                        NAS[[naID]]
                      if (!file.exists(ofile) || overwrite) {
                        if (file.exists(ofile)) {
                          jnk = file.remove(ofile)
                        }
                        lst = list(dataFormat, co, rt, srcnodata, 
                          dstnodata)
                        names(lst) = paste0("-", c("of", 
                          "co", "r", "srcnodata", 
                          "dstnodata"))
                        lst = Filter(Negate(is.null), lst)
                        params = character()
                        for (j in seq(lst)) {
                          params = c(params, names(lst)[j], lst[[j]])
                        }
                        if (is.null(tr) | (!is.null(extent@target) & 
                          t_srs == s_srs)) {
                          sf::gdal_utils(util = "warp", 
                            source = gdalSDS, destination = ofile, 
                            options = c(params, "-overwrite", 
                              "-multi"), quiet = !is.null(opts$quiet) && 
                              opts$quiet)
                          tmp = raster::raster(ofile)
                          if (is.null(tr)) {
                            if (t_srs != s_srs) {
                              tmp = raster::projectExtent(tmp, 
                                crs = t_srs)
                            }
                            tr = raster::res(tmp)
                          }
                          if (!is.null(extent@target$extent) & 
                            t_srs == s_srs) {
                            tmp = raster::crop(tmp, extent@target$extent, 
                              snap = "out")
                            te = as.character(sf::st_bbox(tmp))
                          }
                          rm(tmp)
                        }
                        lst = c(lst, list(`-t_srs` = if (t_srs != 
                          s_srs) t_srs, `-te` = te, `-tr` = tr))
                        lst = Filter(Negate(is.null), lst)
                        for (j in (j + 1):length(lst)) {
                          params = c(params, names(lst)[j], lst[[j]])
                        }
                        jnk = file.remove(ofile)
                        sf::gdal_utils(util = "warp", source = gdalSDS, 
                          destination = ofile, options = c(params, 
                            "-overwrite", "-multi"), 
                          quiet = !is.null(opts$quiet) && opts$quiet)
                      }
                      ofiles[i] <- ofile
                    }
                    lst_ofile[[l]] <- ofiles
                  }
                  else {
                    warning(paste0("No file found for date: ", 
                      avDates[l]))
                    lst_ofile[[l]] <- NA
                  }
                }
                names(lst_ofile) <- avDates
                lst_todo[[u]] <- lst_ofile
            }
            else {
                warning(paste("No", product@PRODUCT, "files found for the period from", 
                  tLimits$begin, "to", paste0(tLimits$end, 
                    ".")))
                lst_todo[[u]] <- NA
            }
        }
        lst_product[[z]] <- lst_todo[[1]]
    }
    names(lst_product) <- paste(product@PRODUCT, product@CCC, 
        sep = ".")
    return(lst_product)
}
Browse[2]> 

Not sure if that is helpful. Thanks Anya

**Comment by fdetsch** [comment]
I deleted everything that is not relevant at this stage from your answer &ndash; hope that's okay. 

From your first post, it looks like you are attempting to download to a temporary folder, which I would not recommend for such big data. Can you do me a favor and set `localArcPath` to a permanent folder on your hard drive? Then verify if the downloaded .hdf file is several 100 MB large or if you're seeing empty files (i.e. something close to 0 kB) only. For example, do the following (remember to change `lap` that defines the local download folder):

```r
library(MODIS)

## enable permanent file storage
lap = "~/Documents/data/MODIS_ARC"
MODISoptions(
  localArcPath = lap
  , outDirPath = file.path(
    lap
    , "PROCESSED"
  )
)

## download data for most recent collection
product = "MOD13Q1"

clc = getCollection(
  product
  , forceCheck = TRUE
)

tfs = runGdal(
  product
  , collection = clc
  , tileH = 20
  , tileV = 11
  , begin = "2000.02.18"
  , end = "2000.02.18"
  , job = "MOD13Q1"
  , SDSstring = "11" # ndvi, evi
)

```

**Comment by Avtober** [comment]
Hi @fdetsch, 

Thanks, I tried that and it created the folder but the folder was empty. I have copied the outcome and the error message below:

Setting 'localArcPath' to 'C:/Users/avtob/OneDrive/Documents/Documents/data/MODIS_ARC'
If you already have downloaded some HDF files, you can use '?orgStruc' to rearrange them.
'outDirPath' has been changed from 'C:/Users/avtob/AppData/Local/Temp/RtmpS2IFWF/MODIS_ARC/PROCESSED/' to 'C:/Users/avtob/OneDrive/Documents/Documents/data/MODIS_ARC/PROCESSED'.
File '~/.MODIS_Opts.R' does not exist. Create it now to make settings permanent? [y/n]: n

STORAGE:
_______________
localArcPath : C:/Users/avtob/OneDrive/Documents/Documents/data/MODIS_ARC 
outDirPath   : C:/Users/avtob/OneDrive/Documents/Documents/data/MODIS_ARC/PROCESSED 


DOWNLOAD:
_______________
MODISserverOrder : LPDAAC, LAADS 
dlmethod         : auto 
stubbornness     : high 
wait             : 0.5 
quiet            : TRUE 


PROCESSING:
_______________
GDAL           : 3.2.1 
MRT            : Enabled 
pixelSize      : asIn 
outProj        : asIn 
resamplingType : NN 
dataFormat     : GTiff 
cellchunk      : 1 


> product = "MOD13Q1"
> clc = getCollection(
+   product
+   , forceCheck = TRUE)
> tfs = runGdal(
+   product
+   , collection = clc
+   , tileH = 20
+   , tileV = 11
+   , begin = "2000.02.18"
+   , end = "2000.02.18"
+   , job = "MOD13Q1"
+   , SDSstring = "11" # ndvi, evi
+ )
########################
outProj          =  asIn 
pixelSize        =  asIn 
resamplingType   =  near 
Output Directory =  C:/Users/avtob/OneDrive/Documents/Documents/data/MODIS_ARC/PROCESSED/MOD13Q1 
########################
Downloading structure on 'LPDAAC' for: MOD13Q1.061
Hm, I have to search for the file. Next time provide the full path and I'll be very fast!
Error in strsplit(x, ":") : non-character argument

Thanks
Anya

**Comment by fdetsch** [comment]
Is a file `~/.netrc` present and are the credentials therein correct?

**Comment by Avtober** [comment]
It brings up the file but it looks like its empty.

**Comment by fdetsch** [comment]
One step closer, I guess. Please run `EarthdataLogin()` and enter your Earthdata credentials (see `?EarthdataLogin` for details). Afterwards, try again the code from https://github.com/MatMatt/MODIS/issues/114#issuecomment-903875483.

**Comment by Avtober** [comment]
I think that worked, I now have a HDF file of around 200,00KB and two Tiff files (NDVI and EVI) in the processed folder! I guess I can try this with the larger data now?

Thanks for your help!
Anya

**Comment by fdetsch** [comment]
Happy to help. Let me know if you encounter other problems.
