### ISSUE TITLE
Can't install MODIS on R version 4.1.1

### ISSUE THREAD

**Issue by olatunjijohnson** [MatMatt/MODIS#117]
install.packages("MODIS")

Warning message:
package ‘MODIS’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by rmdobservations** [comment]
This worked. I have yet to test it further. 
devtools::install_github("MatMatt/MODIS")

**Comment by olatunjijohnson** [comment]
Yes, it works. Thanks. I suppose the problem is the "ref" argument.

**Comment by fdetsch** [comment]
Thanks for solving this. I would recommend sticking to the latest version from GitHub until the package is some day back on CRAN.
