### ISSUE TITLE
library(MODIS) is not working, CANT REINSTALL

### ISSUE THREAD

**Issue by cedlfc44** [MatMatt/MODIS#122]
HI:
I used MODIS during my investigations, today , Im trying to run a code to download EVI images but library MODIS not working, I tried reinstall but :
-When i used github link i get this:
devtools::install_github("MatMatt/MODIS", ref = "develop")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref develop

  Did you spell the repo owner (`MatMatt`) and repo name (`MODIS`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
 
When i load packge from zip file dowload from CRAN i get this:
Installing package into ‘C:/Users/USER/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency 'ptw' is not available for package 'MODIS'
* removing 'C:/Users/USERDocuments/R/win-library/4.1/MODIS'
Warning in install.packages :
  installation of package ‘C:/Users/USER~1/DOWNLO~1/_PACKA~1/MODIS_1.2.3 (1).tar.gz’ had non-zero exit status

Thanks for your help

**Comment by fdetsch** [comment]
The `develop` branch is no longer available. Simply use `remotes::install_github("MatMatt/MODIS")` instead to install from the default branch.
