### ISSUE TITLE
Error with runGdal():  Error in if (FtpDayDirs[1] == FALSE) { :    missing value where TRUE/FALSE needed.     

### ISSUE THREAD

**Issue by rokoeh** [MatMatt/MODIS#15]
While running the command runGdal() I got the following error:

 runGdal(product = "MOD09GQ", tileH = "13", tileV = "11", 
          begin = "2017-01-22", end = "2017-01-27", 
          SDSstring = "0110000000", job = "2016", 
          outProj = "GEO", datum = "WGS84", pixelSize = "0.0023487", 
          mosaic = "FALSE")

  'MRT_HOME' not set/found! MRT is NOT enabled! See: 'https://lpdaac.usgs.gov/tools/modis_reprojection_tool'
Detecting available write drivers!
Found: 69 candidate drivers, detecting file extensions...
44 usable drivers detected!

########################
outProj          =  +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
pixelSize        =  0.0023487 
resamplingType   =  near 
Output Directory =  e:/modis/process//mod09gq/safra2016 
########################
Downloading structure on 'LAADS' for: MOD09GQ.005
                                                                         
Error in if (FtpDayDirs[1] == FALSE) { : 
  missing value where TRUE/FALSE needed

I replicated the error in 2 different machines.

Also when trying to run:  devtools::install_github("MatMatt/MODIS", ref = "release")

devtools::install_github("MatMatt/MODIS", ref = "release")
Downloading GitHub repo MatMatt/MODIS@release
from URL https://api.github.com/repos/MatMatt/MODIS/zipball/release
Error in stop(github_error(request)) : 404: Not Found
 (404)

But this I should report to the devtools package team? (I've been downloading the project from here and sourcing it to install the package MODIS)

With best regards

**Comment by fdetsch** [comment]
Thanks for reporting. It seems like [ftp://ladsftp.nascom.nasa.gov](ftp://ladsftp.nascom.nasa.gov) is currently (permanently?) not reachable. We'll have to check that when time allows. 

As for your second question, the 'release' branch was merged into 'master' as soon as **MODIS** was available from [CRAN](https://CRAN.R-project.org/package=MODIS) and hence no longer exists. Make sure to use the 'develop' branch (`devtools::install_github("MatMatt/MODIS", ref = "develop")`) in order to keep track with latest package updates.

**Comment by khufkens** [comment]
This still works:
ftp://ladsweb.nascom.nasa.gov/

**Comment by fdetsch** [comment]
Now that was sorted out quickly, thanks @khufkens :-)

I changed the relevant LAADS FTP path in "inst/external/MODIS_FTPinfo.RData" and the problem should be fixed as of 10c14a71b6312634449f3dcfd94618ee82e5fa8a. @rokoeh, could you please re-install the 'develop' version and try it out yourself? 

Here's my `sessionInfo()`:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MODIS_1.0.1   raster_2.5-8  sp_1.2-4      mapdata_2.2-6 maps_3.1.1   

loaded via a namespace (and not attached):
 [1] rgdal_1.2-5     parallel_3.3.2  tools_3.3.2     RCurl_1.95-4.8  Rcpp_0.12.9     grid_3.3.2      nloptr_1.0.4   
 [8] ptw_1.9-11      bitops_1.0-6    rgeos_0.3-22    XML_3.98-1.5    lattice_0.20-34

```

**Comment by khufkens** [comment]
I was looking at data recently, and was pretty sure it was still up (although at a different URL). Although I feared for a second that some EO might have taken stuff offline.

**Comment by rokoeh** [comment]
Working just fine now, solved
