### ISSUE TITLE
Can't specify collection in runGdal

### ISSUE THREAD

**Issue by b-p-liu** [MatMatt/MODIS#16]
Hello, I'm trying to process NDVI data in the MOD13Q1 dataset. However, the default collection is v5, whereas I want data from v6. However, if I try to specify the collection number the collection returns as false.

Code:
ext <- MODIS::getTile (tileH=11:13, tileV=3:4)
MODIS::runGdal(product="MOD13Q1", collection= "006", extent=ext, begin="2016.05.24", end="2016.10.14", SDSstring="1", resamplingType="bilinear", outProj= "4326") 

Error Messages:
Product(s) not available in collection '006'. Try 'getCollection('MOD13Q1',newest=FALSE,forceCheck=TRUE)'
Error in if (FtpDayDirs[1] == FALSE) { : 
  missing value where TRUE/FALSE needed

If I try the suggestion:
MODIS::getCollection('MOD13Q1', collection= "006",newest=FALSE,forceCheck=TRUE)
Updating collections from LPDAAC for platform: Terra 
$MOD13Q1
[1] "006"

A note of interest, if I don't specify the collection number, running the code with the .auxiliaries folder in the download destination folder starts the download of v6.

**Comment by MatMatt** [comment]
Using the development version it seems to work fine:
> getCollection('MOD13Q1',newest=FALSE,forceCheck=TRUE)
Updating collections from LPDAAC for platform: Terra 
$MOD13Q1
[1] "005" "006"

please try to install: 
devtools::install_github("MatMatt/MODIS", ref = "develop")

I guess it is connected to this LPDAAC related issue:
https://github.com/MatMatt/MODIS/issues/15

**Comment by b-p-liu** [comment]
I was trying it with the development version. 

The problem was not with the getCollection command. It is when I use runGdal either I specify collection= "006" and the it returns with collection=FALSE and no download occurs or I don't specify collection, then it downloads v5 instead of v6.

Strangely, it will always download v6 the next time the code is executed, due to the .auxiliaries folder, but I would like the code to work the first time around.

**Comment by fdetsch** [comment]
Hm, using the [develop](https://github.com/MatMatt/MODIS/tree/develop) version, your code works perfectly fine for me for both LP DAAC and LAADS. Could you maybe provide the output of `sessionInfo()` and `MODISoptions()`?

**Comment by MatMatt** [comment]
My doubt is that it is a intended behavior that is just a bit badly
communicated.

The ides is that the user has to actively update the getCollection 'file'
to enable a new collection. This is intended in order to not suddenly start
with a new collection without being aware of..

If you still have this issue (after calling): *getCollection('MOD13Q1',*
*newest=FALSE,forceCheck=TRUE)*, than it is a bug. Otherwise it is as
intended, as the error asks you to call getCollection manually.






2017-02-13 17:07 GMT+01:00 Florian Detsch <notifications@github.com>:

**Comment by b-p-liu** [comment]
It seems that I made an error of some sort when installing the develop version. I re-installed it and the code worked fine, sorry for the hassle.
