### ISSUE TITLE
Broken link to 'MODIS' package manual

### ISSUE THREAD

**Issue by fdetsch** [MatMatt/MODIS#2]
The link to the 'MODIS' package manual (shown after `library(MODIS)`) is broken and must either be replaced or removed.

``` r
> library(MODIS)
Loading required package: raster
Loading required package: sp
MODIS_manual: https://ivfl-rio.boku.ac.at/owncloud/public.php?service=files&t=660dc830afb091237cc40b3dea2fdf6b
```

**Comment by MatMatt** [comment]
depends if we aim to release to cran (i would welcome it), we remove, if
not i can continue to maintain it (easy, we can also fix the link an thonk
about cran later)
OK?
Am 01.10.2015 1:12 nachm. schrieb "Florian Detsch" <notifications@github.com

**Comment by fdetsch** [comment]
Removed in preparation for upcoming CRAN release as of 7c1695e2c2684b06702d90fb38c102614763d8ad.
