### ISSUE TITLE
Trouble specifying unique product for runGdal

### ISSUE THREAD

**Issue by jdeines** [MatMatt/MODIS#22]
Hi,
I'm after the 'MOD15A2' product, which I've successfully used in pre-CRAN versions of "MODIS" in the past.  For the most recent version on CRAN, runGdal is failing after downloading tiles for the first date, but before it is able to produce an output composite raster.

I see 'runGdal' uses 'getProduct', and for this product, that returns two - MOD15A2 in collection 5 and MOD15A2H in collection 6.

Using runGdal(product = 'MOD15A2',...) creates two image folders (MODIS, and MODIS.MODIS where images are actually downloaded to) and gives these errors after failing to composite:

1: In genString(x = product$PRODUCT[1], collection = col, local = FALSE) :
  genString() does not support multiple products! Generating 'path' for the first product:MOD15A2
3: In if (info$TYPE == "Tile") { :
  the condition has length > 1 and only the first element will be used

Using runGdal(product = 'MOD15A2H',...) creates only a single MODIS folder with images, and is able to continue processing and output my image composites.

From this, I think there may be a problem with specifying a product name that would return more than 1 from 'getProduct', or perhaps there's just something weird with MOD15A2. If I specify "MOD17A2", getProduct only returns 1 one product, even though there is also a MOD17A2H.

Thoughts?

Thanks for a very useful package!
Jill

**Comment by fdetsch** [comment]
Thanks for reporting this. There are actually several candidate products that likely cause this behavior:

```
library(MODIS)

products = getProduct()[, 2]

dpl = lapply(seq_along(products), function(i) {
  dpl = grep(products[i], products[-i], value = TRUE)
  if (length(dpl) > 0) {
    data.frame(product = products[i], duplicate = dpl)
  } else NULL
})

do.call(rbind, dpl)

   product duplicate
1  MCD15A2  MCD15A2H
2  MCD15A3  MCD15A3H
3    MOD14   MOD14A1
4    MOD14   MOD14A2
5  MOD15A2  MOD15A2H
6  MOD17A2  MOD17A2H
7  MOD17A3  MOD17A3H
8    MYD14   MYD14A1
9    MYD14   MYD14A2
10 MYD15A2  MYD15A2H
11 MYD17A2  MYD17A2H
```

@MatMatt, here's my suggestion: once a user specifies one of the products listed on the left side without including any additional regex symbols (like `*`), we assume that this is the intended target product, and hence, disable pattern matching. This might not be essential for a stand-alone `getProduct()` call, but makes totally sense for `runGdal()`. Do you agree?

**Comment by fdetsch** [comment]
Fixed as of a1ffc43659e1dc8d846d8e337c6f357ccd967b6f, can you please verify @jdeines?

**Comment by fdetsch** [comment]
Closing this issue. If `getProduct()` finds a perfect match, only this product is returned: 

```r
> getProduct("MOD15A2")
MOD15A2 the Composites Tile Leaf Area Index and Fractional Photosynthetically Active Radiation product from MODIS Terra with a ground resolution of 1000 m 

> getProduct("MOD15A2H")
MOD15A2H the Composites Tile Leaf Area Index and Fractional Photosynthetically Active Radiation product from MODIS Terra with a ground resolution of 500 m
```

If you'd like to find any product starting with "MOD15A2", please include `*`:
```r
> getProduct("MOD15A2*")
MOD15A2 the Composites Tile Leaf Area Index and Fractional Photosynthetically Active Radiation product from MODIS Terra with a ground resolution of 1000 m 
MOD15A2H the Composites Tile Leaf Area Index and Fractional Photosynthetically Active Radiation product from MODIS Terra with a ground resolution of 500 m 
```

**Comment by jdeines** [comment]
Looks great, thanks!
