### ISSUE TITLE
MRT path

### ISSUE THREAD

**Issue by steven-higgins** [MatMatt/MODIS#25]
I get the following error message. I am using Linux Ubuntu/Mint. MRT is installed, but MODIS cannot find it and I am not sure where one can specify the path to it. I could of course install MRT to where MODIS is expecting to find it, but I am not sure where it is looking. Many thanks. Steve

MODIS:::checkTools('MRT')
Checking availabillity of MRT:
  'MRT_HOME' not set/found!  MRT is NOT enabled! See: 'https://lpdaac.usgs.gov/tools/modis_reprojection_tool'

**Comment by fdetsch** [comment]
Hi Steve, 

are the `MRT_HOME` and `MRT_DATA_DIR` environment variables setup properly? See also section 'Manual Installation' in the [MRT user manual](https://lpdaac.usgs.gov/sites/default/files/public/mrt41_usermanual_032811.pdf). In my case (Ubuntu 16.04 64-bit), for example, `MRT_HOME` is available from both the terminal
```
fdetsch@fdetsch-ThinkPad-X220:~$ echo $MRT_HOME
/home/fdetsch/apps/mrt
```
and inside R.
```
> Sys.getenv("MRT_HOME")
[1] "/home/fdetsch/apps/mrt"
```

**Comment by steven-higgins** [comment]
excellent tip. Its a new system and I had just installed MRT and needed to reload the .profile to make my system aware of the paths, or as the MODIS_MRT manual says "A system restart is advised to ensure the changes made during MRT installation take effect and the tools function as expected."
thank you for your help

**Comment by fdetsch** [comment]
You are welcome. Just out of curiosity, are you actually processing your data through calling the MRT software from inside **MODIS** (via `runMrt()`) or are you using `runGdal()` instead? 

The reason for why I am asking is that a while back, @MatMatt and me were discussing whether or not to retain MRT functionality in the package since neither of us was actually using it. In this regard, it would be great to have some test users in order to ensure that these (rather dated) functions are still working as intended.

**Comment by steven-higgins** [comment]
I am actually preparing an exercise for teaching. Previously I had used the ModisDownload script and then MRT. I am trying to see if I can reproduce that workflow using your package, doing everything within R. At the moment I am slowly trying to learn the package. Once I have it working I would be happy to share my "tutorial" with you and give you feedback.  The aim is to do this in a way that does not "scare" the students too much :)

**Comment by fdetsch** [comment]
That's a good point (: Just let us know when something is not working as expected - bug reports, enhancements, etc. are always welcome!
