### ISSUE TITLE
Error in runGdal()

### ISSUE THREAD

**Issue by rokoeh** [MatMatt/MODIS#28]
I got some issues with runGdal():

runGdal(product = "MYD09GQ", tileH = 13,
        tileV = 11, begin = "2017.09.25",
         end = "2017.09.25", SDSstring = "0110000000",
         job = "any", outProj = "GEO", datum = "WGS84",
         pixelSize = "0.00225", mosaic = "T" , quiet=T)
########################
outProj          =  +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
pixelSize        =  0.00225 
resamplingType   =  near 
Error in rgdal::rawTransform(projfrom, projto, nrow(xy), xy[, 1], xy[,  : 
  no arguments in initialization list

sessionInfo()

 R version 3.3.2 (2016-10-31) Platform: i386-w64-mingw32/i386 (32-bit) Running under: Windows 7 (build 7601) Service Pack 1 

 locale: [1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    [3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                       [5] LC_TIME=Portuguese_Brazil.1252    

  attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       

other attached packages: [1] MODIS_1.1.0   raster_2.5-8  sp_1.2-5      mapdata_2.2-6 maps_3.2.0     

loaded via a namespace (and not attached):  [1] Rcpp_0.12.9     magrittr_1.5    units_0.4-5     devtools_1.13.3  [5] xtable_1.8-2    lattice_0.20-34 R6_2.2.0        ptw_1.9-12       [9] udunits2_0.13   tools_3.3.2     parallel_3.3.2  rgdal_1.2-12    [13] grid_3.3.2      DBI_0.7         withr_1.0.2     htmltools_0.3.6 [17] mapedit_0.3.2   digest_0.6.12   sf_0.5-3        shiny_1.0.3     [21] nloptr_1.0.4    bitops_1.0-6    RCurl_1.95-4.8  memoise_1.0.0   [25] mime_0.5        XML_3.98-1.9    httpuv_1.3.5

  

 Thanks

**Comment by jac210** [comment]
Hello,
Thank you for this package. I am also running into the same problem when trying to use runGDAL(). 

runGdal(product="MOD44B", collection = "006", begin= "2001001", end= "2001365", tileH = 0, tileV = 7, outProj="EPSG:4326")
########################
outProj  =  +init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
pixelSize  =  asIn 
resamplingType  =  near 
Error in rgdal::rawTransform(projfrom, projto, nrow(xy), xy[, 1], xy[,  : 
 no arguments in initialization list

sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C LC_TIME=English_United States.1252    

attached base packages: [1] stats graphics grDevices utils datasets  methods base     

other attached packages: [1] proj4_1.0-8   rgdal_1.2-13  MODIS_1.1.0   raster_2.5-8  sp_1.2-5 mapdata_2.2-6 maps_3.2.0   

loaded via a namespace (and not attached):
[1] Rcpp_0.12.13  magrittr_1.5 units_0.4-6 devtools_1.13.3 xtable_1.8-2 lattice_0.20-35 R6_2.2.2        ptw_1.9-12 [9] udunits2_0.13 tools_3.4.2 parallel_3.4. grid_3.4.2 DBI_0.7 withr_2.0.0 htmltools_0.3.6 mapedit_0.3.2 [17] digest_0.6.12 sf_0.5-4  shiny_1.0.5 nloptr_1.0.4 bitops_1.0-6 RCurl_1.95-4.8  memoise_1.1.0   mime_0.5 [25] compiler_3.4.2  XML_3.98-1.9 httpuv_1.3.5   
 
Thanks in advance!

**Comment by fdetsch** [comment]
@rokoeh, @jac210 This should be fixed as of https://github.com/MatMatt/MODIS/commit/bf56291dd60bc4812410480ba2778cb480c5ab14. Can you please install the 'develop' version of the package and verify?

@jac210 Even with this bug-fix, you'll most likely encounter the following error:

> No file found for date: 2001-03-06  

MOD44B V006 (and also V051) is not available from LAADS (see ftp://ladsweb.nascom.nasa.gov/allData/6/), and moreover, the .hdf files available for V005 (see ftp://ladsweb.nascom.nasa.gov/allData/5/MOD44B/) seem incomplete. Therefore, you should include

```
# devtools::install_github("MatMatt/MODIS", ref = "develop")
library(MODIS)

MODISoptions(MODISserverOrder = "LPDAAC")
```

to disable download attempts from LAADS, and hence, save some time. However, please note that for this particular product, [LP DAAC](https://e4ftl01.cr.usgs.gov/MOLT/MOD44B.006/) provides tiles from `tileV = 8` onwards only &ndash; at least for `tileH = 0`. 

Moreover, keep in mind that downloading data from LP DAAC requires you to provide Earthdata login credentials (see issue https://github.com/MatMatt/MODIS/issues/14). See also `?lpdaacLogin` for further details. 

In addition, when working on Windows, either use `"wget"` (one of the more recent versions like 1.19.2 provided [here](https://eternallybored.org/misc/wget/), NOT the last "official" Windows release [1.11.4](http://gnuwin32.sourceforge.net/packages/wget.htm) dating back from 2008...) or `"curl"` as download method passed to `MODISoptions(dlmethod = ...)`. For example, on my machine, the following code works just fine:

```
MODISoptions(MODISserverOrder = "LPDAAC"
             , dlmethod = "wget"
             , outProj = "+init=epsg:4326")

tfs1 = runGdal(product = "MOD44B", collection = "006"
               , begin= "2001001", end = "2001365"
               , tileH = 0, tileV = 8
               , job = "debug-mod44b")
```

```
> tfs1

$MOD44B.006
$MOD44B.006$`2001-03-06`
[1] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Percent_Tree_Cover.tif"        
[2] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Percent_NonTree_Vegetation.tif"
[3] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Percent_NonVegetated.tif"      
[4] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Quality.tif"                   
[5] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Percent_Tree_Cover_SD.tif"     
[6] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Percent_NonVegetated_SD.tif"   
[7] "D:/programming/r/MODIS/MODIS_ARC/PROCESSED/debug-mod44b/MOD44B.A2001065.Cloud.tif"
```
