### ISSUE TITLE
Error in runGdal....  GDAL not installed or configured.....

### ISSUE THREAD

**Issue by rsmiller74** [MatMatt/MODIS#30]
I have tried several potential solutions on stackover flow but none have resolved issue.  Same problem happens with version of MODIS on cran and also the developer version.

> devtools::install_github("MatMatt/MODIS", ref = "develop")
Skipping install of 'MODIS' from a github remote, the SHA1 (9b054e99) has not changed since last install.   

> require(MODIS)
> ## get options
> #MODISoptions() 
> ## set options
> MODISoptions(localArcPath="D:/MODIS/")  
 
> dates <- as.POSIXct( as.Date(c("01/05/2014","31/05/2014"),format = "%d/%m/%Y") )
> dates2 <- transDate(dates[1],dates[2]) # Transform input dates from before
> h = "21"
> v = "09"
> runGdal(product=product,begin=dates2$beginDOY,end = dates2$endDOY,tileH = h,tileV = v,) 

Error in runGdal(product = product, begin = dates2$beginDOY, end = dates2$endDOY,  : 
GDAL not installed or configured, read in '?MODISoptions' for help

> sessionInfo() 

R version 3.4.1 (2017-06-30) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 7 x64 (build 7601) Service Pack 1  Matrix products: default  locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] MODIS_1.1.1   raster_2.6-7  sp_1.2-5      mapdata_2.2-6 maps_3.2.0     loaded via a namespace (and not attached):  [1] Rcpp_0.12.14    compiler_3.4.1  nloptr_1.0.4    git2r_0.19.0    bitops_1.0-6    class_7.3-14    tools_3.4.1      [8] digest_0.6.12   memoise_1.1.0   lattice_0.20-35 shiny_1.0.5     DBI_0.7         curl_3.0        rgdal_1.2-16    [15] parallel_3.4.1  e1071_1.6-8     withr_2.1.0     httr_1.3.1      devtools_1.13.4 classInt_0.1-24 mapedit_0.3.2   [22] grid_3.4.1      sf_0.5-5        R6_2.2.2        ptw_1.9-12      XML_3.98-1.9    udunits2_0.13   magrittr_1.5    [29] htmltools_0.3.6 units_0.4-6     mime_0.5        xtable_1.8-2    httpuv_1.3.5    RCurl_1.95-4.8
--

**Comment by fdetsch** [comment]
Seems like the package is not able to detect GDAL. What's your output of `MODIS:::checkTools()`? Here's what mine looks like:

```
> MODIS:::checkTools()
Checking availabillity of MRT:
  'MRT_HOME' found: C:/Program Files (x86)/MODIS Reprojection Tool 
  'MRT_DATA_DIR' found: C:/Program Files (x86)/MODIS Reprojection Tool/data 
   MRT enabled, settings are fine!
Checking availability of 'FWTools/OSGeo4W' (GDAL with HDF4 support for Windows):
   OK, GDAL 2.2.1, released 2017/06/23 found!
```

**Comment by fdetsch** [comment]
@rsmiller74 Did you have the chance to run the above code?
