### ISSUE TITLE
Unclear error when HDF4 support is lacking

### ISSUE THREAD

**Issue by bart1** [MatMatt/MODIS#32]
I just tried to get runGdal running on a osx machine, gdal2 gets installed there without HDF4 support. The problem is that checktools returns without an issue but the gdalOk variable gets set to false, I could only figure out by traceing my way throught the source that this was due to hdf4 support lacking. I think the error reporting here needs to be improved, by forexample throwing a warning here: https://github.com/MatMatt/MODIS/blob/52c29ebf327bbaf2216abc99b4df6da744570ce6/R/doOptions.R#L203
```
> MODIS:::checkTools("gdal")
Checking availabillity of GDAL:
   OK, GDAL 2.2.3, released 2017/11/20 found!
```

**Comment by fdetsch** [comment]
Sounds like the perfect opportunity for a pull request to me (in particular since I cannot test this on OSX) :-)

@bart1, would you like to take care of this using the current 'develop' branch as reference?

**Comment by fdetsch** [comment]
From now on, a `warning()` is thrown when HDF4 support is lacking.
