### ISSUE TITLE
getTile("Philippines") bug

### ISSUE THREAD

**Issue by nbarsch** [MatMatt/MODIS#34]
getTile("countrynamehere") works as far as I have found EXCEPT with getTile("Philippines")

Code:
getTile("Philippines")
Error in createPolygonsComment(p) : 
  rgeos_PolyCreateComment: orphaned hole, cannot find containing polygon for hole at index 1

**Comment by fdetsch** [comment]
Fixed as of https://github.com/MatMatt/MODIS/commit/1b14974063b371a69987e5ee218ee66f132b2d61. This error was actually related to some non-valid geometries in **maps**, which became evident when converting a particular 'map' object to 'Spatial*' and in preparation for `raster::crop()`. In fact, not only the Philippines, but also countries like Spain were affected, see for example

```
m1 = map("worldHires", "Spain", plot = FALSE, fill = TRUE)
p1 = maptools::map2SpatialPolygons(m1, IDs = m1$names, proj4string = CRS("+init=epsg:4326"))
rgeos::gIsValid(p1)
```
> [1] FALSE
> Warning message:
> In RGEOSUnaryPredFunc(spgeom, byid, "rgeos_isvalid") :
>   Self-intersection at or near point -6.7722642984582979 41.090799814136382

Anyway, this should now be settled. After installing the 'develop' version of **MODIS**, `getTile("Philippines")` (and, for that matter, also `getTile("Spain")`) should run smoothly.

**Comment by nbarsch** [comment]
Thanks fdetsch.
