### ISSUE TITLE
LP DAAC access Username/Password Authentication lpdaacLogin

### ISSUE THREAD

**Issue by WillemVervoort** [MatMatt/MODIS#45]
Sorry, I first posted this in a "closed" issue, I think I need to open a new issue

Hi all, this remains a problem. I have used lpdaacLogin() and have no problem with creating netrc
Windows, R3.4.3

I am also logged in into Earthdata via a web browser
MODISoptions(MODISserverOrder = "LPDAAC")

product = "MOD16A2"
lpdaacLogin()

hdf = getHdf("MOD16A2", begin = "2017.01.01", end = "2017.01.10",
tileH = 21, tileV = 8)
hdf

Resolving urs.earthdata.nasa.gov (urs.earthdata.nasa.gov)... 198.118.243.33
Connecting to urs.earthdata.nasa.gov (urs.earthdata.nasa.gov)|198.118.243.33|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

Any clues?

**Comment by WillemVervoort** [comment]
This is the same issues as #44

**Comment by Lynettelaw** [comment]
Dear Willem,
I have exactly the same problem with you. May I know if you have solved this?

Thank you very much!

**Comment by WillemVervoort** [comment]
I didn't I took another approach, you will have to e-mail me directly if
you want me to share
I'll need to dig it out somewhere

willemvervoort@gmail.com
