### ISSUE TITLE
Error in getHdf only on Windows

### ISSUE THREAD

**Issue by Piso67** [MatMatt/MODIS#49]
When i'm running my MODIS Download R script on my Windows, i'll get this error :

    `############################
    Remote connection failed! Re-try: 49 
    Getting file from: LPDAAC 
    ############################`
After this, the script crashes because it tried to do gdalinfo on an inexisting image.
I'm just doing getHdf function on LPDAAC servers using my EarthExplorer Username and Password. I'll get this error on 3 different Windows PC, my personnal computer, university computer and a friend pc so on three different networks. My code runs perfectly on my Mac, do you have any idea ? 

    `MODISoptions(gdalPath = gdalPath, MODISserverOrder = "LPDAAC")
  
    #We have to log in into lpdaac servers using NASAs ID and password
    lpdaacLogin(server = "LPDAAC")

    image <- getHdf(product = "MOD09GA", begin = toString(currentDate), end = toString(currentDate), extent = c(longMin, longMax, latMin, latMax))`

Here is my ModisOptions() :

    `'MRT_HOME' not set/found! MRT is NOT enabled! See: 
    'https://lpdaac.usgs.gov/tools/modis_reprojection_tool'

     STORAGE:
     _______________
     localArcPath : C:/Users/Romain/AppData/Local/Temp/RtmpGUSr8w/MODIS_ARC/ 
     outDirPath   : 
     C:/Users/Romain/AppData/Local/Temp/RtmpGUSr8w/MODIS_ARC/PROCESSED/ 

     DOWNLOAD:
     _______________
     MODISserverOrder : LPDAAC 
     dlmethod         : auto 
     stubbornness     : high 
     wait             : 0.5 
     quiet            : FALSE 

     PROCESSING:
     _______________
     GDAL           : GDAL 2.2.4, released 2018/03/19 
     MRT            : Not available. Use 'MODIS:::checkTools('MRT')' for more 
     information! 
     pixelSize      : asIn 
     outProj        : asIn 
     resamplingType : NN 
     dataFormat     : GTiff `

Note : i choosed LPDAAC because LAADS FTP servers are down since the 20 april 2018.

``

**Comment by fdetsch** [comment]
There have been some changes to `getHdf()` lately, could you please re-run your code and see if it works now? Alternatively, data download from LAADS, which migrated to HTTPS, is now re-enabled in **MODIS**. Hence, you could try this with `MODISoptions(MODISserverOrder = c("LAADS", "LPDAAC"))` as well. Just make sure to install the current 'develop' version as these changes not on CRAN, yet: 

```r
devtools::install_github("MatMatt/MODIS", ref = "develop")
```

**Comment by Piso67** [comment]
Thanks, LAADS works well now. I will try as soon as possible on Windows.
