### ISSUE TITLE
"MODIS package's runGdal() returns error: dataFormat" problem

### ISSUE THREAD

**Issue by tnauss** [MatMatt/MODIS#5]
As a follow up to this discussion

http://r-sig-geo.2731867.n2.nabble.com/MODIS-package-s-runGdal-returns-error-dataFormat-GTiff-format-not-supported-td7589869.html

I think the error is related to (a potential?) change in gdal format names. In your function "gdalWriteDriver" (minorFuns.R) in line 337, I assume you expect something like "VRT" but what you get is "VRT-raster-". The same is true for all others. 

I have cloned your develop branch  and added

`name          <- sapply(name, function(x){return(strsplit(x, "-")[[1]][1])})`

in line 338.

As far I can tell from a quick look - works fine.

Cheers
Thomas

**Comment by fdetsch** [comment]
Fixed in package version `0.10-34` ('develop' branch). Thanks for the help!

**Comment by PauloEduardoCardoso** [comment]
I'm getting the "dataFormat='GTiff'" error runing version 0.10-34.

**Comment by Fulano-LeTal** [comment]
I'm getting the same error in version 0.10-34: `dataFormat='GTiff', format not supported by GDAL`
If I try:
```
> getOption("MODIS_gdalOutDriver")
[1] name        description extension  
<0 rows> (or 0-length row.names)
```
Some sugestions?
