### ISSUE TITLE
Invalid connection with getHdf (using most recent dev MODIS version)

### ISSUE THREAD

**Issue by nbarsch** [MatMatt/MODIS#51]
`m17 <- getHdf(product = "M.D17A3", begin = "2013.01.01", tileH = 20:21, tileV = 9)`

Error message:
Updating collection from LPDAAC for product: MOD17A3 
No end(-date) set, getting data up to the most actual
Error in if (FtpDayDirs[1] == FALSE) { : 
  missing value where TRUE/FALSE needed
Error in close.connection(file) : invalid connection

**Comment by fdetsch** [comment]
Fixed as of 227e0b1f00ca98d5dee81eb51dbb18e56f458de5, can you please verify? 

```r
m17 <- getHdf(product = "M.D17A3", begin = "2013.01.01", tileH = 20:21, tileV = 9)
m17
# $`MOD17A3.055`
# [1] "C:/.../MODIS_~1/MODIS/MOD17A3.055/2013.01.01/MOD17A3.A2013001.h20v09.055.2016008110330.hdf"
# [2] "C:/.../MODIS_~1/MODIS/MOD17A3.055/2013.01.01/MOD17A3.A2013001.h21v09.055.2016008110446.hdf"
# [3] "C:/.../MODIS_~1/MODIS/MOD17A3.055/2014.01.01/MOD17A3.A2014001.h20v09.055.2016008120820.hdf"
# [4] "C:/.../MODIS_~1/MODIS/MOD17A3.055/2014.01.01/MOD17A3.A2014001.h21v09.055.2016008120843.hdf"
```
