### ISSUE TITLE
HDF4 driver seems to be lacking. Please install GDAL with HDF4 support.

### ISSUE THREAD

**Issue by BenMDawson** [MatMatt/MODIS#56]
When I run the MODIS command to find GDAL:
```
> MODIS:::checkTools('GDAL')

Checking availability of GDAL:
   OK, GDAL 2.3.1, released 2018/06/22 found!
```

However,
```
> MODISoptions()

...
PROCESSING:
_______________
GDAL           : Not available. Use 'MODIS:::checkTools('GDAL')' for more information! 
...
```

When I first run the code I get an error: `HDF4 driver seems to be lacking. Please install GDAL with HDF4 support.`

Though in terminal (I'm on a mac) I get:
```
USER$ gdalinfo --format HDF4
Format Details:
  Short Name: HDF4
  Long Name: Hierarchical Data Format Release 4
  Supports: Raster
  Extension: hdf
  Help Topic: frmt_hdf4.html
  Supports: Subdatasets
  Supports: Open() - Open existing dataset.
```

About my R environment

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

**Comment by BenMDawson** [comment]
I needed to point to a different GDAL package (using conda).

**Comment by fdetsch** [comment]
Always glad to receive feedback from macOS users. Let us know if you encounter any further difficulties.

**Comment by BenMDawson** [comment]
It doesn't return anything - making me think that it doesn't find `gdalinfo`.

**Comment by fdetsch** [comment]
Ah sorry, I meant `intern = TRUE` - in case gdalinfo couldn't be found, this should print an error to the console.

**Comment by BenMDawson** [comment]
```
> system("which gdalinfo", intern = T)
character(0)
attr(,"status")
[1] 1
Warning message:
In system("which gdalinfo", intern = T) :
  running command 'which gdalinfo' had status 1
```

**Comment by fdetsch** [comment]
Hmm, seems indeed like R cannot find it. Have you already tried any of the solutions provided [here](https://gis.stackexchange.com/questions/130710/system-call-gdal-function-in-r-on-mac)?

**Comment by BenMDawson** [comment]
I have it working, and I pretty much followed the link you have provided above. The directions I provided above solve the issue. I have `MODIS` working perfectly now - thank you for the great package.

**Comment by fdetsch** [comment]
Thanks, really appreciate it! Glad to hear this worked out for you.
