### ISSUE TITLE
getTile() sp subset or raster::crop issues with PROJ 6.1 and GDAL 3.0

### ISSUE THREAD

**Issue by rsbivand** [MatMatt/MODIS#71]
During revdep checks for rgdal, I see that the getTile() example faila with `identicalCRS(x, y) is not TRUE`. This is my `debug()` output:
```
Browse[2]> class(x)
[1] "SpatialPolygonsDataFrame"
attr(,"package")
[1] "sp"
Browse[2]> class(sr)
[1] "SpatialPolygonsDataFrame"
attr(,"package")
[1] "sp"
Browse[2]> proj4string(x)
[1] "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
Browse[2]> proj4string(sr)
[1] "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
Browse[2]> 
debug: sr[x, ]
Browse[2]> 
Error in .local(x, y, returnList, fn, ...) : 
  identicalCRS(x, y) is not TRUE
```
I think that this is similar to https://github.com/riatelab/cartography/issues/54 and https://github.com/USGS-R/inlmisc/issues/106, where the **inlmisc** issue is for a topology error in `raster::crop()` which you use in the other `if()` branch in not used here (here you use `"["`).

**Comment by fdetsch** [comment]
For future reference: https://stat.ethz.ch/pipermail/r-sig-geo/2019-November/027801.html. 

@rsbivand, I'll implement required changes asap.
