### ISSUE TITLE
Error object a not found

### ISSUE THREAD

**Issue by goergen95** [MatMatt/MODIS#72]
The error from the headline shows up when using the function whittaker.raster when outputAs is set as "one"
I narrowed it down to this line of code, where it should be changed to:
```
 names(b[[1]]) <- timeInfo$outputLayerDates
```
The letter **a** seems to be an artifact from the other methods where **a** represents an iterator.

https://github.com/MatMatt/MODIS/blob/ff083536fe8143bb420ad4fb4232eca5ae604be5/R/whittaker.R#L237

**Comment by MatMatt** [comment]
Okay! Changed in develop, thanks!
Ok now?

**Comment by goergen95** [comment]
Thanks! Works Great!

**Comment by MatMatt** [comment]
Ok, thanks!

goergen95 <notifications@github.com> schrieb am Fr., 14. Juni 2019, 10:33:

**Comment by fdetsch** [comment]
Thanks for sorting this out, guys!
