### ISSUE TITLE
whittaker.raster does not exclude NAs in the weights raster

### ISSUE THREAD

**Issue by jacobmardian** [MatMatt/MODIS#73]
The whittaker.raster function handles NA values in the vi and t inputs by changing their corresponding values in the "set0" matrix to true:

line 267: set0[is.na(val)] <- TRUE
line 301: set0[is.na(inTu)] <- TRUE

However, this is not done for the weights input raster. When using the MODIS VI Quality layer, there are many NA values that should be excluded from analysis due to unknown pixel quality (or otherwise handled via user parameters). 

This problem can be addressed by inserting the following code on line 291:
set0[is.na(wtu)] <- TRUE

**Comment by MatMatt** [comment]
Thanks! I have changed in develop. 
I see the 0 in wtu are handled correctly but the NA's in wtu were not converted. 
Ok now?

**Comment by fdetsch** [comment]
@jacobmardian can you please verify?

**Comment by jacobmardian** [comment]
Yes this has been resolved in the develop version. Thank you.
