### ISSUE TITLE
runGdal function couldn't get tif files

### ISSUE THREAD

**Issue by Fay07** [MatMatt/MODIS#80]
I tried to get MOD17A2H product, all hdf files were downloaded but there is no tiff file converted. Please see attached code. Thanks. 

library(MODIS)
library(raster)
MODISoptions(MODISserverOrder = c("LAADS", "LPDAAC")) 
EarthdataLogin()
path = 'D:/downloadMODIS'
lap <- file.path(path, "MODIS_ARC") # 'localArcPath'
odp <- file.path(lap, "PROCESSED")  # 'outDirPath'
MODISoptions(localArcPath = lap, outDirPath = odp)

aoi_usa <- getData('GADM', country = 'USA', level = 1)
aoi_ca <- aoi_usa[aoi_usa$NAME_1 == "California",]

runGdal(job = "gpp", product = 'MOD17A2H', extent = extent(aoi_ca), begin = '2000.01.01', end = '2019.12.31')

**Comment by fdetsch** [comment]
Works perfectly fine for me. If you do 

```r
library(MODIS)
MODISoptions(MODISserverOrder = c("LPDAAC", "LAADS"))

aoi_usa <- getData('GADM', country = 'USA', level = 1, path = tmpDir())
aoi_ca <- aoi_usa[aoi_usa$NAME_1 == "California",]

tfs = runGdal(job = "gpp", product = 'MOD17A2H', extent = aoi_ca, begin = '2019.03.01', end = '2019.06.30')
```

what's the content of `tfs`? It should look something like this: 

```r
> tfs
$MOD17A2H.006
$MOD17A2H.006$`2019-02-26`
[1] "~/../Data/MODIS_ARC/PROCESSED/gpp/MOD17A2H.A2019057.Gpp_500m.tif"   
[2] "~/../Data/MODIS_ARC/PROCESSED/gpp/MOD17A2H.A2019057.PsnNet_500m.tif"
[3] "~/../Data/MODIS_ARC/PROCESSED/gpp/MOD17A2H.A2019057.Psn_QC_500m.tif"

$MOD17A2H.006$`2019-03-06`
[1] "~/../Data/MODIS_ARC/PROCESSED/gpp/MOD17A2H.A2019065.Gpp_500m.tif"   
[2] "~/../Data/MODIS_ARC/PROCESSED/gpp/MOD17A2H.A2019065.PsnNet_500m.tif"
[3] "~/../Data/MODIS_ARC/PROCESSED/gpp/MOD17A2H.A2019065.Psn_QC_500m.tif"

...
```
Also, note that LAADS download is [currently not possible](https://github.com/MatMatt/MODIS/issues/77).

**Comment by Fay07** [comment]
It works now. Thank you.
