### ISSUE TITLE
Raster with no default name

### ISSUE THREAD

**Issue by safalabolo** [MatMatt/MODIS#81]
Hi!
Input raster data (Vegetation indices and Cloud mask) with names in yyyymmdd format can be used instead of yyyydoy Thanks in advance for the response.
All the Best.

**Comment by fdetsch** [comment]
I am not quite sure I understand what you are suggesting. Can you maybe provide an example (code and resulting layers)?

**Comment by fdetsch** [comment]
Closing this due to lack of response.
