### ISSUE TITLE
MODIS not downloading GeoTIFFs?

### ISSUE THREAD

**Issue by dkcorvus86** [MatMatt/MODIS#83]
Hi Matt,

I am brand new to using MODIS and doing spatial analyses. I am using the code from [eBird best practices](https://cornelllabofornithology.github.io/ebird-best-practices/covariates.html). All data is available via the best practices page. I have download GDAL and installed the MODIS package. Everything appears to work when I run the following code to obtain MODIS tiles for the appropriate BCR region: 
```bcr <- read_sf("data/gis-data.gpkg", "bcr") %>% 
  filter(bcr_code == 27) %>% 
  st_transform(crs = paste("+proj=sinu +lon_0=0 +x_0=0 +y_0=0",
                           "+a=6371007.181 +b=6371007.181 +units=m +no_defs"))

ebird <- read_csv("data/ebd_woothr_june_bcr27_zf.csv")
tiles <- getTile(bcr)

begin_year <- format(min(ebird$observation_date), "%Y.01.01")
end_year <- format(max(ebird$observation_date), "%Y.12.31")

tifs <- runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
                extent = bcr %>% st_buffer(dist = 10000), 
                begin = begin_year, end = end_year, 
                outDirPath = "data", job = "modis",
                MODISserverOrder = "LPDAAC") %>% 
  pluck("MCD12Q1.006") %>% 
  unlist()
 ```
When I run the runGdal() command it returns the following:
>Hm, I have to search for the file! Next time provide the full path and I'll be very fast!

It repeats this 30+ times and then finishing running. In the modis folder, there are no GeoTIFFs or any other file. 

I apologize if this is a repeat of a previous issue. I ran through issues, looking for a similar problem, but couldn't find one. Any help would be appreciated.

**Comment by fdetsch** [comment]
Works on my side. Maybe same issue as [here](https://github.com/MatMatt/MODIS/issues/82)?

**Comment by dkcorvus86** [comment]
That didn't seem to work. I went back to ```EarthdataLogin()``` and reentered my credentials, the same problem emerged. I went to their website and double checked that those are the correct credentials. 

When I run 
```
tifs <- runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
                extent = bcr %>% st_buffer(dist = 10000), 
                begin = begin_year, end = end_year, 
                outDirPath = "data", job = "modis",
                MODISserverOrder = "LPDAAC") %>% 
  pluck("MCD12Q1.006") %>% 
  unlist()
```

it returns 
>########################
outProj          =  +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs  (if applicable, derived from Raster*/Spatial*/sf* object)
pixelSize        =  asIn 
resamplingType   =  near 
Output Directory =  F:/ebird/data/modis 
########################
Downloading structure on 'LPDAAC' for: MCD12Q1.006
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!
Hm, I have to search for the file! Next time provide the full path and I'll be very fast!

and then keeps going until it gives up.

It sometimes replaces 
>Downloading structure on 'LPDAAC' for: MCD12Q1.006

with

>Local structure is up-to-date. Using offline information!


my sessionInfo() is
>R version 3.6.2 (2019-12-12)
>Platform: x86_64-w64-mingw32/x64 (64-bit)
>Running under: Windows 7 x64 (build 7601) Service Pack 1

>Matrix products: default

>locale:
>[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
>[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
>[5] LC_TIME=English_United States.1252    

>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
 >[1] forcats_0.4.0     stringr_1.4.0     dplyr_0.8.4       purrr_0.3.3      
 >[5] readr_1.3.1       tidyr_1.0.2       tibble_2.1.3      ggplot2_3.2.1    
 >[9] tidyverse_1.3.0   viridis_0.5.1     viridisLite_0.3.0 velox_0.2.0      
>[13] MODIS_1.1.6       mapdata_2.3.0     maps_3.3.0        raster_3.0-12    
>[17] sp_1.3-2          sf_0.8-1         

>loaded via a namespace (and not attached):
 >[1] nlme_3.1-142       bitops_1.0-6       fs_1.3.1           usethis_1.5.1     
 >[5] lubridate_1.7.4    devtools_2.2.2     httr_1.4.1         rprojroot_1.3-2   
 >[9] tools_3.6.2        backports_1.1.5    rgdal_1.4-8        R6_2.4.1          
>[13] KernSmooth_2.23-16 rgeos_0.5-2        DBI_1.1.0          lazyeval_0.2.2    
>[17] colorspace_1.4-1   withr_2.1.2        tidyselect_1.0.0   gridExtra_2.3     
>[21] prettyunits_1.1.1  processx_3.4.2     curl_4.3           compiler_3.6.2    
>[25] rvest_0.3.5        cli_2.0.1          xml2_1.2.2         desc_1.2.0        
>[29] scales_1.1.0       classInt_0.4-2     callr_3.4.2        digest_0.6.24     
>[33] foreign_0.8-72     pkgconfig_2.0.3    htmltools_0.4.0    sessioninfo_1.1.1 
>[37] dbplyr_1.4.2       fastmap_1.0.1      readxl_1.3.1       rlang_0.4.4       
>[41] rstudioapi_0.11    shiny_1.4.0        generics_0.0.2     jsonlite_1.6.1    
>[45] magrittr_1.5       Rcpp_1.0.3         munsell_0.5.0      fansi_0.4.1       
>[49] lifecycle_0.1.0    stringi_1.4.6      pkgbuild_1.0.6     grid_3.6.2        
>[53] maptools_0.9-9     parallel_3.6.2     promises_1.1.0     crayon_1.3.4      
>[57] lattice_0.20-38    haven_2.2.0        hms_0.5.3          ps_1.3.2          
>[61] pillar_1.4.3       codetools_0.2-16   pkgload_1.0.2      reprex_0.3.0      
>[65] glue_1.3.1         remotes_2.1.1      modelr_0.1.6       vctrs_0.2.2       
>[69] nloptr_1.2.1       httpuv_1.5.2       cellranger_1.1.0   testthat_2.3.1    
>[73] gtable_0.3.0       assertthat_0.2.1   mime_0.9           xtable_1.8-4      
>[77] broom_0.5.4        e1071_1.7-3        later_1.0.0        class_7.3-15      
>[81] memoise_1.1.0      ptw_1.9-15         units_0.6-5        mapedit_0.6.0     
>[85] ellipsis_0.3.0    

```
MODISoptions() 
```
returns

>STORAGE:
>_______________
>localArcPath : C:/Users/Koz/AppData/Local/Temp/RtmpUzwYXs/MODIS_ARC/ 
>outDirPath   : C:/Users/Koz/AppData/Local/Temp/RtmpUzwYXs/MODIS_ARC/PROCESSED/ 


>DOWNLOAD:
>_______________
>MODISserverOrder : LPDAAC 
>dlmethod         : auto 
>stubbornness     : high 
>wait             : 0.5 
>quiet            : TRUE 


>PROCESSING:
>_______________
>GDAL           : GDAL 3.0.4, released 2020/01/28 
>MRT            : Enabled 
>pixelSize      : asIn 
>outProj        : asIn 
>resamplingType : NN 
>dataFormat     : GTiff 
>cellchunk      : 1

**Comment by fdetsch** [comment]
I reran the code using a temporary `localArcPath` (like you do) instead of a permanent folder, but still couldn't reproduce this behavior. Are there any .hdf files downloaded to your temporary `localArcPath` before the freeze?

**Comment by dkcorvus86** [comment]
Nope. Nothing gets created in that temporary path other then a folder MODIS with empty subfolders corresponding to each attempted date and the PROCESSED output folder which has some .auxilliaries

**Comment by fdetsch** [comment]
That can be easily tested. For example, can you download [this file](https://e4ftl01.cr.usgs.gov/MOTA/MCD12Q1.006/2010.01.01/MCD12Q1.A2010001.h18v02.006.2018146000104.hdf) after entering your Earthdata username and password?

**Comment by dkcorvus86** [comment]
That file downloaded no problem.

**Comment by dkcorvus86** [comment]
If i add the LAADS server to the ```MODISserverOrder = c("LPDAAC","LAADS"))``` to the ```runGdal()``` code above, I get 3 HDF files downloaded into each of the temporary folders for ```2010.01.01...2019.01.01```, but nothing for the remaining dates of the year and it does not process them into annual GeoTIFFs so nothing appears in the output folder ```data/modis/```

**Comment by dkcorvus86** [comment]
I was able to get this to work, by specifying the ```MODISoptions(dlmethod = 'curl')```.
Oddly  enough if i specify ```MODISoptions(dlmethod = 'wget')``` it appears to work, but never completes the job. So it seems like there was some issue with the ```dlmethod = 'auto'```
