### ISSUE TITLE
gap filling reflectance with linear interpolation approach

### ISSUE THREAD

**Issue by safalabolo** [MatMatt/MODIS#87]
Hi,
Is a temporal gap-filling of bands reflectance possible through an approach based on simple linear interpolation with MODIS package?Thanks in advance for reply

**Comment by fdetsch** [comment]
No, this is beyond the scope of **MODIS**, which offers two filtering techniques for vegetation indices (`whittaker.raster()`, `smooth.spline.raster()`) only. 

How about [`approxNA`](https://www.rdocumentation.org/packages/raster/versions/3.1-5/topics/approxNA) from **raster** to perform linear interpolation between layers?
