### ISSUE TITLE
Automated adjustment of 'pos1,pos2'

### ISSUE THREAD

**Issue by fdetsch** [MatMatt/MODIS#9]
When working with newly introduced, higher-resolution vegetation products (e.g. [MCD15A2H](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd15a2h_v006)), it would be nice to adjust arguments `pos1,pos2` automatically. Otherwise, functions like `whittaker.raster` (which relies on `orgTime`) are bound to fail since date strings in the product's filename do no longer start and end at the 10th and 16th position, respectively.

**Comment by MatMatt** [comment]
Could you please send me an updated version of MODIS_Products.RData (your fun addProduct). Then I can automatize the extraction of the date from the filenames in general.

**Comment by fdetsch** [comment]
It's already available from the 'develop' branch. For instance, if you run

`devtools::install_github("MatMatt/MODIS", ref = "develop")`

then `getProduct()` will include the newly added products.

**Comment by fdetsch** [comment]
This is available as of e1c39b5c98981a2eda08ee126f59524e730d0552.
