### ISSUE TITLE
error when runMrt example:'mrtmosaic'  Not an internal or external command, and not a runnable program Or batch files.

### ISSUE THREAD

**Issue by shimudongren** [MatMatt/MODIS#97]
when i run the examplle
geo = runMrt(product="MOD11A1", extent="austria", begin="2010001", end="2010002", SDSstring="101",
+              job="ExampleGEOdelme", outProj="GEO")

occure follow errors:
'mrtmosaic'  Not an internal or external command, and not a runnable program Or batch files.
'resample'  Not an internal or external command, and not a runnable program Or batch files.

Before installing the **modis** package, do i should install mrttool from modis web?
i notice that the **mrttool** in the modis web have retired.

**Comment by fdetsch** [comment]
I strongly recommend using `runGdal()` instead. `runMrt()` has primarily been kept inside the package to account for backward compatibility, although the software [has been retired a good while ago](https://lpdaac.usgs.gov/news/we-are-preparing-retirement-downloadable-modis-reprojection-tool-mrt-and-mrtswath-tool/) (I believe the last update was in 2011).

If you, for whatever reason, really want to try out MRT, you'll need to retrieve the software installer from somewhere, install and set environment variables `MRT_HOME` and `MRT_DATA_DIR` accordingly. You can then verify your installation via 

```r
MODIS:::checkTools("MRT")
# Checking availability of MRT:
#   'MRT_HOME' found: C:/MRT 
#   'MRT_DATA_DIR' found: C:/MRT/data 
#    MRT enabled, settings are fine!
```
